### ISSUE TITLE
Consulta 5 SQL - Más de 1 tabla con INNER JOIN y con filtros

### ISSUE THREAD

**Issue by amayabren** [amayabren/Proyecto-Integrador#5]

**Comment by florlelli** [comment]
**Detalles**

- Objetivo:
Obtener un listado de ventas realizadas en el año 2023, filtradas para incluir solo aquellas con un monto superior a 100, y desglosadas por cliente y producto.

- Pasos para la creación de la consulta:

1. Identificación de Tablas Relevantes:

-ventas: Contiene la información de las ventas, incluyendo el monto y la fecha.
-clientes: Contiene la información de los clientes, como el nombre.
-productos: Contiene la información de los productos, como el nombre y el precio.

2. Definición de Relaciones:

-ventas se relaciona con clientes a través del campo cliente_id.
-ventas se relaciona con productos a través del campo producto_id.

3. Construcción de la Consulta:

-INNER JOIN entre ventas y clientes para obtener el nombre del cliente.
-INNER JOIN entre ventas y productos para obtener el nombre del producto.

4. Filtros:

-Ventas realizadas en el año 2023 (YEAR(ventas.fecha) = 2023).
-Monto de la venta superior a 200.000 (ventas.monto > 200.000).

-Consulta SQL Final:

**sql
Copiar código
SELECT clientes.nombre AS nombre_cliente, productos.nombre AS nombre_producto, ventas.fecha, ventas.monto
FROM ventas
INNER JOIN clientes ON ventas.cliente_id = clientes.cliente_id
INNER JOIN productos ON ventas.producto_id = productos.producto_id
WHERE YEAR(ventas.fecha) = 2023
AND ventas.monto > 200.000;**
